TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

DB += pico8_frib_chan_trip.db
DB += pico8.db
DB += pico8_frib.db
DB += pico8_chan_alias.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
