#!../../bin/linux-x86_64/pico

# !!! This file was autogenerated by epics-driver/gen-iocs/gen.py

< envPaths

epicsEnvSet("EPICS_CA_MAX_ARRAY_BYTES","10000000")
epicsEnvSet("ENGINEER", "diag")
epicsEnvSet("DIAGSTD_DISABLE_STATS", "YES")

dbLoadDatabase("../../dbd/pico.dbd",0,0)
pico_registerRecordDeviceDriver(pdbbase)

# slot numbers from /sys/bus/pci/slots/*/address
createPICO8("PICO3", "/dev/amc_pico_0000:08:00.0")
createPICO8("PICO4", "/dev/amc_pico_0000:06:00.0")
createPICO8("PICO5", "/dev/amc_pico_0000:09:00.0")
createPICO8("PICO6", "/dev/amc_pico_0000:0b:00.0")
createPICO8("PICO7", "/dev/amc_pico_0000:0f:00.0")
createPICO8("PICO8", "/dev/amc_pico_0000:0d:00.0")

# (SYS):(D)_CHX:Y_Z
dbLoadRecords("../../db/pico8_frib.db","SYS=DIAG_MTCA15,D=PICO3,NAME=PICO3,NELM=1000000")
dbLoadRecords("../../db/pico8_frib.db","SYS=DIAG_MTCA15,D=PICO4,NAME=PICO4,NELM=1000000")
dbLoadRecords("../../db/pico8_frib.db","SYS=DIAG_MTCA15,D=PICO5,NAME=PICO5,NELM=1000000")
dbLoadRecords("../../db/pico8_frib.db","SYS=DIAG_MTCA15,D=PICO6,NAME=PICO6,NELM=1000000")
dbLoadRecords("../../db/pico8_frib.db","SYS=DIAG_MTCA15,D=PICO7,NAME=PICO7,NELM=1000000")
dbLoadRecords("../../db/pico8_frib.db","SYS=DIAG_MTCA15,D=PICO8,NAME=PICO8,NELM=1000000")

< $(TOP)/iocBoot/archiver_tags.cmd

# record name aliases
# (SYS):(D)_CHX:Y_Z -> (A)Y_Z

# Slot 3
reAddAlias "DIAG_MTCA15:PICO3_CH0:(.*)" "FE_LEBT:PM_D0945:A_$1"
reAddAlias "DIAG_MTCA15:PICO3_CH1:(.*)" "FE_LEBT:PM_D0945:B_$1"
reAddAlias "DIAG_MTCA15:PICO3_CH2:(.*)" "FE_LEBT:PM_D0945:C_$1"
reAddAlias "DIAG_MTCA15:PICO3_CH4:(.*)" "FE_LEBT:PM_D0961:A_$1"
reAddAlias "DIAG_MTCA15:PICO3_CH5:(.*)" "FE_LEBT:PM_D0961:B_$1"
reAddAlias "DIAG_MTCA15:PICO3_CH6:(.*)" "FE_LEBT:PM_D0961:C_$1"

# Slot 4
reAddAlias "DIAG_MTCA15:PICO4_CH0:(.*)" "FE_LEBT:PM_D0972:A_$1"
reAddAlias "DIAG_MTCA15:PICO4_CH1:(.*)" "FE_LEBT:PM_D0972:B_$1"
reAddAlias "DIAG_MTCA15:PICO4_CH2:(.*)" "FE_LEBT:PM_D0972:C_$1"
reAddAlias "DIAG_MTCA15:PICO4_CH4:(.*)" "FE_LEBT:PM_D0986:A_$1"
reAddAlias "DIAG_MTCA15:PICO4_CH5:(.*)" "FE_LEBT:PM_D0986:B_$1"
reAddAlias "DIAG_MTCA15:PICO4_CH6:(.*)" "FE_LEBT:PM_D0986:C_$1"

# Slot 5
reAddAlias "DIAG_MTCA15:PICO5_CH0:(.*)" "FS2_BBS:PM_D4051:A_$1"
reAddAlias "DIAG_MTCA15:PICO5_CH1:(.*)" "FS2_BBS:PM_D4051:B_$1"
reAddAlias "DIAG_MTCA15:PICO5_CH2:(.*)" "FS2_BBS:PM_D4051:C_$1"
reAddAlias "DIAG_MTCA15:PICO5_CH4:(.*)" "FS2_BMS:PM_D4144:A_$1"
reAddAlias "DIAG_MTCA15:PICO5_CH5:(.*)" "FS2_BMS:PM_D4144:B_$1"
reAddAlias "DIAG_MTCA15:PICO5_CH6:(.*)" "FS2_BMS:PM_D4144:C_$1"

# Slot 6
reAddAlias "DIAG_MTCA15:PICO6_CH0:(.*)" "FS2_BTS:PM_D3959:A_$1"
reAddAlias "DIAG_MTCA15:PICO6_CH1:(.*)" "FS2_BTS:PM_D3959:B_$1"
reAddAlias "DIAG_MTCA15:PICO6_CH2:(.*)" "FS2_BTS:PM_D3959:C_$1"
reAddAlias "DIAG_MTCA15:PICO6_CH4:(.*)" "FS2_BTS:PM_D4009:A_$1"
reAddAlias "DIAG_MTCA15:PICO6_CH5:(.*)" "FS2_BTS:PM_D4009:B_$1"
reAddAlias "DIAG_MTCA15:PICO6_CH6:(.*)" "FS2_BTS:PM_D4009:C_$1"

# Slot 7
reAddAlias "DIAG_MTCA15:PICO7_CH0:(.*)" "FS2_BBS:IC_D4055:$1"
reAddAlias "DIAG_MTCA15:PICO7_CH1:(.*)" "FS2_BBS:IC_D4018:$1"
reAddAlias "DIAG_MTCA15:PICO7_CH2:(.*)" "FS2_BBS:IC_D3979:$1"
reAddAlias "DIAG_MTCA15:PICO7_CH4:(.*)" "FS2_BTS:IC_D4018:$1"
reAddAlias "DIAG_MTCA15:PICO7_CH5:(.*)" "FS2_BTS:IC_D3940:$1"
reAddAlias "DIAG_MTCA15:PICO7_CH6:(.*)" "FS2_BBS:IC_D4102:$1"

# Slot 8
reAddAlias "DIAG_MTCA15:PICO8_CH2:(.*)" "FS2_BTS:IC_D4019:$1"


< $(TOP)/iocBoot/archiver_chan_tags.cmd

## Start the PICO python helper script
system "python3 ../../iocBoot/scripts/blm_processing_thread.py DIAG_MTCA15:PICO3 DIAG_MTCA15:PICO4 DIAG_MTCA15:PICO5 DIAG_MTCA15:PICO6 DIAG_MTCA15:PICO7 DIAG_MTCA15:PICO8 &"

iocInit()

## Set PICO card AMC slot numbers on startup for each card.
dbpf "DIAG_MTCA15:PICO3_FPS:SLT_CSET", "3"
dbpf "DIAG_MTCA15:PICO4_FPS:SLT_CSET", "4"
dbpf "DIAG_MTCA15:PICO5_FPS:SLT_CSET", "5"
dbpf "DIAG_MTCA15:PICO6_FPS:SLT_CSET", "6"
dbpf "DIAG_MTCA15:PICO7_FPS:SLT_CSET", "7"
dbpf "DIAG_MTCA15:PICO8_FPS:SLT_CSET", "8"

