#!../../bin/linux-x86_64/pico

# !!! This file was autogenerated by epics-driver/gen-iocs/gen.py

< envPaths

epicsEnvSet("EPICS_CA_MAX_ARRAY_BYTES","10000000")
epicsEnvSet("ENGINEER", "diag")

dbLoadDatabase("../../dbd/pico.dbd",0,0)
pico_registerRecordDeviceDriver(pdbbase)

# slot numbers from /sys/bus/pci/slots/*/address
createPICO8("PICO11", "/dev/amc_pico_0000:0a:00.0")

# (SYS):(D)_CHX:Y_Z
dbLoadRecords("../../db/pico8_frib.db","SYS=DIAG_MTCA02,D=PICO11,NAME=PICO11,NELM=1000000")

< $(TOP)/iocBoot/archiver_tags.cmd

# record name aliases
# (SYS):(D)_CHX:Y_Z -> (A)Y_Z

# Slot 11
reAddAlias "DIAG_MTCA02:PICO11_CH0:(.*)" "LS1_CA01:HMR_D0001:$1"
reAddAlias "DIAG_MTCA02:PICO11_CH1:(.*)" "LS1_CA01:HMR_D0002:$1"
reAddAlias "DIAG_MTCA02:PICO11_CH2:(.*)" "LS1_CA01:HMR_D0003:$1"
reAddAlias "DIAG_MTCA02:PICO11_CH3:(.*)" "LS1_CA01:HMR_D0004:$1"
reAddAlias "DIAG_MTCA02:PICO11_CH4:(.*)" "LS1_CA01:HMR_D0005:$1"
reAddAlias "DIAG_MTCA02:PICO11_CH5:(.*)" "LS1_CA01:HMR_D0006:$1"
reAddAlias "DIAG_MTCA02:PICO11_CH6:(.*)" "LS1_CA01:HMR_D0007:$1"
reAddAlias "DIAG_MTCA02:PICO11_CH7:(.*)" "LS1_CA01:HMR_D0008:$1"


< $(TOP)/iocBoot/archiver_chan_tags.cmd

## Start the PICO python helper script
system "python ../../iocBoot/scripts/blm_processing_thread.py DIAG_MTCA02:PICO11 &"

iocInit()

## Set PICO card AMC slot numbers on startup for each card.
dbpf "DIAG_MTCA02:PICO11_FPS:SLT_CSET", "11"

