#!../../bin/linux-x86_64/pico

# !!! This file was autogenerated by epics-driver/gen-iocs/gen.py

< envPaths

epicsEnvSet("EPICS_CA_MAX_ARRAY_BYTES","10000000")
epicsEnvSet("ENGINEER", "diag")
epicsEnvSet("DIAGSTD_DISABLE_STATS", "YES")

dbLoadDatabase("../../dbd/pico.dbd",0,0)
pico_registerRecordDeviceDriver(pdbbase)

# slot numbers from /sys/bus/pci/slots/*/address
createPICO8("PICO3", "/dev/amc_pico_0000:08:00.0")
createPICO8("PICO4", "/dev/amc_pico_0000:06:00.0")

# (SYS):(D)_CHX:Y_Z
dbLoadRecords("../../db/pico8_frib.db","SYS=DIAG,SSYS=MTCA03,NAME=PICO3")
dbLoadRecords("../../db/pico8_frib.db","SYS=DIAG,SSYS=MTCA03,NAME=PICO4")

< $(TOP)/iocBoot/archiver_tags.cmd

# record name aliases
# (SYS):(D)_CHX:Y_Z -> (A)Y_Z

# Slot 3
reAddAlias "DIAG_MTCA03:PICO3_CH0:(.*)" "FS2_BMS:IC_D4141:$1"
reAddAlias "DIAG_MTCA03:PICO3_CH1:(.*)" "FS2_BMS:IC_D4180:$1"
reAddAlias "DIAG_MTCA03:PICO3_CH2:(.*)" "FS2_BMS:IC_D4221:$1"
reAddAlias "DIAG_MTCA03:PICO3_CH3:(.*)" "FS2_BMS:IC_D4277:$1"
reAddAlias "DIAG_MTCA03:PICO3_CH4:(.*)" "FS2_BMS:IC_D4305:$1"
reAddAlias "DIAG_MTCA03:PICO3_CH5:(.*)" "LS3_CD01:IC_D4385:$1"
reAddAlias "DIAG_MTCA03:PICO3_CH6:(.*)" "LS3_CD03:IC_D4503:$1"

# Slot 4
reAddAlias "DIAG_MTCA03:PICO4_CH0:(.*)" "LS1_WA03:BD_D1224:$1"
reAddAlias "DIAG_MTCA03:PICO4_CH4:(.*)" "FS2_BMS:HMR_D4328:$1"
reAddAlias "DIAG_MTCA03:PICO4_CH5:(.*)" "LS3_WD04:HMR_D4576:$1"


< $(TOP)/iocBoot/archiver_chan_tags.cmd

## Start the PICO python helper script
system "python3 ../../iocBoot/scripts/blm_processing_thread.py DIAG_MTCA03:PICO3 DIAG_MTCA03:PICO4 &"

iocInit()

## Set PICO card AMC slot numbers on startup for each card.
dbpf "DIAG_MTCA03:PICO3_FPS:SLT_CSET", "3"
dbpf "DIAG_MTCA03:PICO4_FPS:SLT_CSET", "4"

