# !!! This file was autogenerated by gen-archiver-tags/gen-tags.py
# !!! https://stash.frib.msu.edu/projects/DIAG/repos/gen-archiver-tags/
# !!! gen-tags.py Pico8-chan
  
reAddInfo ".*:EMS_D.*[_:]AVG_RD$"  "archive" "monitor:2, retention:1m"
reAddInfo ".*:FC_D.*[_:]AVG_RD$"   "archive" "monitor:2"
reAddInfo ".*:FC_D.*[_:]AVGS_RD$"  "archive" "monitor:0.5, retention:1m"
reAddInfo ".*:FC_D.*[_:]LAVG_RD$"  "archive" "monitor:1, retention:1m"
reAddInfo ".*:FC_D.*[_:]STD_RD$"   "archive" "monitor:1, retention:1m"
reAddInfo ".*:HMR_D.*[_:]AVG_RD$"  "archive" "monitor:2"
reAddInfo ".*:HMR_D.*[_:]AVGS_RD$" "archive" "monitor:0.5, retention:1m"
reAddInfo ".*:HMR_D.*[_:]LAVG_RD$" "archive" "monitor:1, retention:1m"
reAddInfo ".*:HMR_D.*[_:]STD_RD$"  "archive" "monitor:1, retention:1m"
reAddInfo ".*:IC_D.*[_:]AVG_RD$"   "archive" "monitor:2"
reAddInfo ".*:IC_D.*[_:]AVGS_RD$"  "archive" "monitor:0.5, retention:1m"
reAddInfo ".*:IC_D.*[_:]LAVG_RD$"  "archive" "monitor:1, retention:1m"
reAddInfo ".*:IC_D.*[_:]STD_RD$"   "archive" "monitor:1, retention:1m"
reAddInfo ".*:ND_D.*[_:]AVG_RD$"   "archive" "monitor:2"
reAddInfo ".*:ND_D.*[_:]AVGS_RD$"  "archive" "monitor:0.5, retention:1m"
reAddInfo ".*:ND_D.*[_:]LAVG_RD$"  "archive" "monitor:1, retention:1m"
reAddInfo ".*:ND_D.*[_:]STD_RD$"   "archive" "monitor:1, retention:1m"
reAddInfo ".*:PM_D.*[_:]AVG_RD$"   "archive" "monitor:2, retention:1m"
